//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.Server.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class SkyTelescope : global::System.Configuration.ApplicationSettingsBase {
        
        private static SkyTelescope defaultInstance = ((SkyTelescope)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SkyTelescope())));
        
        public static SkyTelescope Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
            set {
                this["Version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ps9600")]
        public string BaudRate {
            get {
                return ((string)(this["BaudRate"]));
            }
            set {
                this["BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AlignmentMode {
            get {
                return ((string)(this["AlignmentMode"]));
            }
            set {
                this["AlignmentMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlternatingPPEC {
            get {
                return ((bool)(this["AlternatingPPEC"]));
            }
            set {
                this["AlternatingPPEC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double ApertureDiameter {
            get {
                return ((double)(this["ApertureDiameter"]));
            }
            set {
                this["ApertureDiameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool AtPark {
            get {
                return ((bool)(this["AtPark"]));
            }
            set {
                this["AtPark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoTrack {
            get {
                return ((bool)(this["AutoTrack"]));
            }
            set {
                this["AutoTrack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int DataBits {
            get {
                return ((int)(this["DataBits"]));
            }
            set {
                this["DataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisconnectOnPark {
            get {
                return ((bool)(this["DisconnectOnPark"]));
            }
            set {
                this["DisconnectOnPark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DTREnable {
            get {
                return ((bool)(this["DTREnable"]));
            }
            set {
                this["DTREnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double Elevation {
            get {
                return ((double)(this["Elevation"]));
            }
            set {
                this["Elevation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EncodersOn {
            get {
                return ((bool)(this["EncodersOn"]));
            }
            set {
                this["EncodersOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("equTopocentric")]
        public string EquatorialCoordinateType {
            get {
                return ((string)(this["EquatorialCoordinateType"]));
            }
            set {
                this["EquatorialCoordinateType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.26")]
        public double FocalLength {
            get {
                return ((double)(this["FocalLength"]));
            }
            set {
                this["FocalLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string HandShake {
            get {
                return ((string)(this["HandShake"]));
            }
            set {
                this["HandShake"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double HomeAxisX {
            get {
                return ((double)(this["HomeAxisX"]));
            }
            set {
                this["HomeAxisX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double HomeAxisY {
            get {
                return ((double)(this["HomeAxisY"]));
            }
            set {
                this["HomeAxisY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double HourAngleLimit {
            get {
                return ((double)(this["HourAngleLimit"]));
            }
            set {
                this["HourAngleLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15.0369")]
        public double KingRate {
            get {
                return ((double)(this["KingRate"]));
            }
            set {
                this["KingRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("56.76")]
        public double Latitude {
            get {
                return ((double)(this["Latitude"]));
            }
            set {
                this["Latitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5.85")]
        public double Longitude {
            get {
                return ((double)(this["Longitude"]));
            }
            set {
                this["Longitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14.685")]
        public double LunarRate {
            get {
                return ((double)(this["LunarRate"]));
            }
            set {
                this["LunarRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Simulator")]
        public string Mount {
            get {
                return ((string)(this["Mount"]));
            }
            set {
                this["Mount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Seven")]
        public string HcSpeed {
            get {
                return ((string)(this["HcSpeed"]));
            }
            set {
                this["HcSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ReadTimeout {
            get {
                return ((int)(this["ReadTimeout"]));
            }
            set {
                this["ReadTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RTSEnable {
            get {
                return ((bool)(this["RTSEnable"]));
            }
            set {
                this["RTSEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15.0410671787")]
        public double SiderealRate {
            get {
                return ((double)(this["SiderealRate"]));
            }
            set {
                this["SiderealRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double SolarRate {
            get {
                return ((double)(this["SolarRate"]));
            }
            set {
                this["SolarRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TraceLogger {
            get {
                return ((bool)(this["TraceLogger"]));
            }
            set {
                this["TraceLogger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RATrackingOffset {
            get {
                return ((int)(this["RATrackingOffset"]));
            }
            set {
                this["RATrackingOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0269")]
        public double ApertureArea {
            get {
                return ((double)(this["ApertureArea"]));
            }
            set {
                this["ApertureArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double Temperature {
            get {
                return ((double)(this["Temperature"]));
            }
            set {
                this["Temperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double GuideRateOffsetX {
            get {
                return ((double)(this["GuideRateOffsetX"]));
            }
            set {
                this["GuideRateOffsetX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double GuideRateOffsetY {
            get {
                return ((double)(this["GuideRateOffsetY"]));
            }
            set {
                this["GuideRateOffsetY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanAlignMode {
            get {
                return ((bool)(this["CanAlignMode"]));
            }
            set {
                this["CanAlignMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanAltAz {
            get {
                return ((bool)(this["CanAltAz"]));
            }
            set {
                this["CanAltAz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanDoesRefraction {
            get {
                return ((bool)(this["CanDoesRefraction"]));
            }
            set {
                this["CanDoesRefraction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanEquatorial {
            get {
                return ((bool)(this["CanEquatorial"]));
            }
            set {
                this["CanEquatorial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanFindHome {
            get {
                return ((bool)(this["CanFindHome"]));
            }
            set {
                this["CanFindHome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanLatLongElev {
            get {
                return ((bool)(this["CanLatLongElev"]));
            }
            set {
                this["CanLatLongElev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanOptics {
            get {
                return ((bool)(this["CanOptics"]));
            }
            set {
                this["CanOptics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanPark {
            get {
                return ((bool)(this["CanPark"]));
            }
            set {
                this["CanPark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool CanPierSide {
            get {
                return ((bool)(this["CanPierSide"]));
            }
            set {
                this["CanPierSide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanPulseGuide {
            get {
                return ((bool)(this["CanPulseGuide"]));
            }
            set {
                this["CanPulseGuide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanSetEquRates {
            get {
                return ((bool)(this["CanSetEquRates"]));
            }
            set {
                this["CanSetEquRates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanSetGuideRates {
            get {
                return ((bool)(this["CanSetGuideRates"]));
            }
            set {
                this["CanSetGuideRates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanSetPark {
            get {
                return ((bool)(this["CanSetPark"]));
            }
            set {
                this["CanSetPark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanSetPierSide {
            get {
                return ((bool)(this["CanSetPierSide"]));
            }
            set {
                this["CanSetPierSide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanSetTracking {
            get {
                return ((bool)(this["CanSetTracking"]));
            }
            set {
                this["CanSetTracking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanSiderealTime {
            get {
                return ((bool)(this["CanSiderealTime"]));
            }
            set {
                this["CanSiderealTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanSlew {
            get {
                return ((bool)(this["CanSlew"]));
            }
            set {
                this["CanSlew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanSlewAltAz {
            get {
                return ((bool)(this["CanSlewAltAz"]));
            }
            set {
                this["CanSlewAltAz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanSlewAltAzAsync {
            get {
                return ((bool)(this["CanSlewAltAzAsync"]));
            }
            set {
                this["CanSlewAltAzAsync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanSlewAsync {
            get {
                return ((bool)(this["CanSlewAsync"]));
            }
            set {
                this["CanSlewAsync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanSync {
            get {
                return ((bool)(this["CanSync"]));
            }
            set {
                this["CanSync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanUnpark {
            get {
                return ((bool)(this["CanUnpark"]));
            }
            set {
                this["CanUnpark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanSyncAltAz {
            get {
                return ((bool)(this["CanSyncAltAz"]));
            }
            set {
                this["CanSyncAltAz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanTrackingRates {
            get {
                return ((bool)(this["CanTrackingRates"]));
            }
            set {
                this["CanTrackingRates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NoSyncPastMeridian {
            get {
                return ((bool)(this["NoSyncPastMeridian"]));
            }
            set {
                this["NoSyncPastMeridian"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int NumMoveAxis {
            get {
                return ((int)(this["NumMoveAxis"]));
            }
            set {
                this["NumMoveAxis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VersionOne {
            get {
                return ((bool)(this["VersionOne"]));
            }
            set {
                this["VersionOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("driveSidereal")]
        public string TrackingRate {
            get {
                return ((string)(this["TrackingRate"]));
            }
            set {
                this["TrackingRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Refraction {
            get {
                return ((bool)(this["Refraction"]));
            }
            set {
                this["Refraction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DecBacklash {
            get {
                return ((int)(this["DecBacklash"]));
            }
            set {
                this["DecBacklash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int St4Guiderate {
            get {
                return ((int)(this["St4Guiderate"]));
            }
            set {
                this["St4Guiderate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.5")]
        public double MaximumSlewRate {
            get {
                return ((double)(this["MaximumSlewRate"]));
            }
            set {
                this["MaximumSlewRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RaBacklash {
            get {
                return ((int)(this["RaBacklash"]));
            }
            set {
                this["RaBacklash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int GpsPort {
            get {
                return ((int)(this["GpsPort"]));
            }
            set {
                this["GpsPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string CdCip {
            get {
                return ((string)(this["CdCip"]));
            }
            set {
                this["CdCip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3292")]
        public int CdCport {
            get {
                return ((int)(this["CdCport"]));
            }
            set {
                this["CdCport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HomeWarning {
            get {
                return ((bool)(this["HomeWarning"]));
            }
            set {
                this["HomeWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanSetDeclinationRate {
            get {
                return ((bool)(this["CanSetDeclinationRate"]));
            }
            set {
                this["CanSetDeclinationRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CanSetRightAscensionRate {
            get {
                return ((bool)(this["CanSetRightAscensionRate"]));
            }
            set {
                this["CanSetRightAscensionRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ASCOM GS Sky Telescope")]
        public string InstrumentDescription {
            get {
                return ((string)(this["InstrumentDescription"]));
            }
            set {
                this["InstrumentDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GSServer")]
        public string InstrumentName {
            get {
                return ((string)(this["InstrumentName"]));
            }
            set {
                this["InstrumentName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.001")]
        public double GotoPrecision {
            get {
                return ((double)(this["GotoPrecision"]));
            }
            set {
                this["GotoPrecision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FullCurrent {
            get {
                return ((bool)(this["FullCurrent"]));
            }
            set {
                this["FullCurrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int DisplayInterval {
            get {
                return ((int)(this["DisplayInterval"]));
            }
            set {
                this["DisplayInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Axes")]
        public string HCMode {
            get {
                return ((string)(this["HCMode"]));
            }
            set {
                this["HCMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ParkPositions {
            get {
                return ((string)(this["ParkPositions"]));
            }
            set {
                this["ParkPositions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string ParkName {
            get {
                return ((string)(this["ParkName"]));
            }
            set {
                this["ParkName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DecPulseToGoTo {
            get {
                return ((bool)(this["DecPulseToGoTo"]));
            }
            set {
                this["DecPulseToGoTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool LimitTracking {
            get {
                return ((bool)(this["LimitTracking"]));
            }
            set {
                this["LimitTracking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MinPulseRa {
            get {
                return ((int)(this["MinPulseRa"]));
            }
            set {
                this["MinPulseRa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MinPulseDec {
            get {
                return ((int)(this["MinPulseDec"]));
            }
            set {
                this["MinPulseDec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int SyncLimit {
            get {
                return ((int)(this["SyncLimit"]));
            }
            set {
                this["SyncLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ps4800")]
        public string GpsBaudRate {
            get {
                return ((string)(this["GpsBaudRate"]));
            }
            set {
                this["GpsBaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan UTCOffset {
            get {
                return ((global::System.TimeSpan)(this["UTCOffset"]));
            }
            set {
                this["UTCOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HcAntiRa {
            get {
                return ((bool)(this["HcAntiRa"]));
            }
            set {
                this["HcAntiRa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HcAntiDec {
            get {
                return ((bool)(this["HcAntiDec"]));
            }
            set {
                this["HcAntiDec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SpiralPause {
            get {
                return ((int)(this["SpiralPause"]));
            }
            set {
                this["SpiralPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int SpiralSpeed {
            get {
                return ((int)(this["SpiralSpeed"]));
            }
            set {
                this["SpiralSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4800")]
        public int SpiralFov {
            get {
                return ((int)(this["SpiralFov"]));
            }
            set {
                this["SpiralFov"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4800")]
        public int SpiralWidth {
            get {
                return ((int)(this["SpiralWidth"]));
            }
            set {
                this["SpiralWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4800")]
        public int SpiralHeight {
            get {
                return ((int)(this["SpiralHeight"]));
            }
            set {
                this["SpiralHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double SpiralDistance {
            get {
                return ((double)(this["SpiralDistance"]));
            }
            set {
                this["SpiralDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpiralLimits {
            get {
                return ((bool)(this["SpiralLimits"]));
            }
            set {
                this["SpiralLimits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CameraWidth {
            get {
                return ((double)(this["CameraWidth"]));
            }
            set {
                this["CameraWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CameraHeight {
            get {
                return ((double)(this["CameraHeight"]));
            }
            set {
                this["CameraHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double EyepieceFS {
            get {
                return ((double)(this["EyepieceFS"]));
            }
            set {
                this["EyepieceFS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PpecOn {
            get {
                return ((bool)(this["PpecOn"]));
            }
            set {
                this["PpecOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PecOn {
            get {
                return ((bool)(this["PecOn"]));
            }
            set {
                this["PecOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PecOffSet {
            get {
                return ((int)(this["PecOffSet"]));
            }
            set {
                this["PecOffSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PecWormFile {
            get {
                return ((string)(this["PecWormFile"]));
            }
            set {
                this["PecWormFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Pec360File {
            get {
                return ((string)(this["Pec360File"]));
            }
            set {
                this["Pec360File"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PecWorm")]
        public string PecMode {
            get {
                return ((string)(this["PecMode"]));
            }
            set {
                this["PecMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool LimitPark {
            get {
                return ((bool)(this["LimitPark"]));
            }
            set {
                this["LimitPark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ParkLimitName {
            get {
                return ((string)(this["ParkLimitName"]));
            }
            set {
                this["ParkLimitName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SyncLimitOn {
            get {
                return ((bool)(this["SyncLimitOn"]));
            }
            set {
                this["SyncLimitOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CustomRaWormTeeth {
            get {
                return ((int)(this["CustomRaWormTeeth"]));
            }
            set {
                this["CustomRaWormTeeth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CustomDecWormTeeth {
            get {
                return ((int)(this["CustomDecWormTeeth"]));
            }
            set {
                this["CustomDecWormTeeth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CustomRa360Steps {
            get {
                return ((int)(this["CustomRa360Steps"]));
            }
            set {
                this["CustomRa360Steps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CustomDec360Steps {
            get {
                return ((int)(this["CustomDec360Steps"]));
            }
            set {
                this["CustomDec360Steps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CustomRaTrackingOffset {
            get {
                return ((int)(this["CustomRaTrackingOffset"]));
            }
            set {
                this["CustomRaTrackingOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CustomDecTrackingOffset {
            get {
                return ((int)(this["CustomDecTrackingOffset"]));
            }
            set {
                this["CustomDecTrackingOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CustomGearing {
            get {
                return ((bool)(this["CustomGearing"]));
            }
            set {
                this["CustomGearing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GlobalStopOn {
            get {
                return ((bool)(this["GlobalStopOn"]));
            }
            set {
                this["GlobalStopOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HcFlipEW {
            get {
                return ((bool)(this["HcFlipEW"]));
            }
            set {
                this["HcFlipEW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HcFlipNS {
            get {
                return ((bool)(this["HcFlipNS"]));
            }
            set {
                this["HcFlipNS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PolarLedLevel {
            get {
                return ((int)(this["PolarLedLevel"]));
            }
            set {
                this["PolarLedLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RaGaugeFlip {
            get {
                return ((bool)(this["RaGaugeFlip"]));
            }
            set {
                this["RaGaugeFlip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string FrontGraphic {
            get {
                return ((string)(this["FrontGraphic"]));
            }
            set {
                this["FrontGraphic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double AxisTrackingLimit {
            get {
                return ((double)(this["AxisTrackingLimit"]));
            }
            set {
                this["AxisTrackingLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowAdvancedCommandSet {
            get {
                return ((bool)(this["AllowAdvancedCommandSet"]));
            }
            set {
                this["AllowAdvancedCommandSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string Port {
            get {
                return ((string)(this["Port"]));
            }
            set {
                this["Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2500")]
        public int AltAzTrackingUpdateInterval {
            get {
                return ((int)(this["AltAzTrackingUpdateInterval"]));
            }
            set {
                this["AltAzTrackingUpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool HzLimitTracking {
            get {
                return ((bool)(this["HzLimitTracking"]));
            }
            set {
                this["HzLimitTracking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ParkHzLimitName {
            get {
                return ((string)(this["ParkHzLimitName"]));
            }
            set {
                this["ParkHzLimitName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool HzLimitPark {
            get {
                return ((bool)(this["HzLimitPark"]));
            }
            set {
                this["HzLimitPark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double AxisHzTrackingLimit {
            get {
                return ((double)(this["AxisHzTrackingLimit"]));
            }
            set {
                this["AxisHzTrackingLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HomeDialog {
            get {
                return ((bool)(this["HomeDialog"]));
            }
            set {
                this["HomeDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ParkDialog {
            get {
                return ((bool)(this["ParkDialog"]));
            }
            set {
                this["ParkDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double AxisUpperLimitY {
            get {
                return ((double)(this["AxisUpperLimitY"]));
            }
            set {
                this["AxisUpperLimitY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double AxisLowerLimitY {
            get {
                return ((double)(this["AxisLowerLimitY"]));
            }
            set {
                this["AxisLowerLimitY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double AxisLimitX {
            get {
                return ((double)(this["AxisLimitX"]));
            }
            set {
                this["AxisLimitX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModelType {
            get {
                return ((string)(this["ModelType"]));
            }
            set {
                this["ModelType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AxisModelOffsets {
            get {
                return ((string)(this["AxisModelOffsets"]));
            }
            set {
                this["AxisModelOffsets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[0,0]")]
        public string ParkAxes {
            get {
                return ((string)(this["ParkAxes"]));
            }
            set {
                this["ParkAxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{""Speed"":1,""Duration"":1000,""Interval"":1000,""Rate"":0.012},{""Speed"":2,""Duration"":1000,""Interval"":1000,""Rate"":0.024},{""Speed"":3,""Duration"":1000,""Interval"":1000,""Rate"":0.165},{""Speed"":4,""Duration"":1000,""Interval"":1000,""Rate"":0.238},{""Speed"":5,""Duration"":1000,""Interval"":1000,""Rate"":0.7},{""Speed"":6,""Duration"":1000,""Interval"":1000,""Rate"":1.4},{""Speed"":7,""Duration"":1000,""Interval"":1000,""Rate"":2.8},{""Speed"":8,""Duration"":1000,""Interval"":1000,""Rate"":3.5}]")]
        public string HcPulseGuides {
            get {
                return ((string)(this["HcPulseGuides"]));
            }
            set {
                this["HcPulseGuides"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableKeysOnGoTo {
            get {
                return ((bool)(this["DisableKeysOnGoTo"]));
            }
            set {
                this["DisableKeysOnGoTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PolarMode {
            get {
                return ((string)(this["PolarMode"]));
            }
            set {
                this["PolarMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double AutoHomeAxisX {
            get {
                return ((double)(this["AutoHomeAxisX"]));
            }
            set {
                this["AutoHomeAxisX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double AutoHomeAxisY {
            get {
                return ((double)(this["AutoHomeAxisY"]));
            }
            set {
                this["AutoHomeAxisY"] = value;
            }
        }
    }
}
